# Travis-CI build script for KaHyPar

language: cpp

# Ubuntu 14.04 Trusty support
sudo: required
dist: trusty

matrix:
  include:
    # gcc 6 - Debug Build
    - env: CMAKE_CC="gcc-6" CMAKE_CXX="g++-6" BUILD_TYPE="Debug" COMPILER_FLAGS=""
      os: linux
      addons: &gcc6
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - cmake-data
            - g++-6
            - libboost-program-options1.55.0
            - libboost-program-options1.55-dev

    # gcc 6 - Release Build
    - env: CMAKE_CC="gcc-6" CMAKE_CXX="g++-6" BUILD_TYPE="Release" COMPILER_FLAGS=""
      os: linux
      addons: *gcc6

      # gcc 6 - RelWithDebInfo Build - end to end tests
    - env: CMAKE_CC="gcc-6" CMAKE_CXX="g++-6" BUILD_TYPE="RelWithDebInfo" COMPILER_FLAGS=""
      os: linux
      addons: *gcc6

    # clang 3.7 on MacOSX
    - env: CMAKE_CC="clang" CMAKE_CXX="clang++" BUILD_TYPE="Debug" COMPILER_FLAGS=""
      os: osx

    - env: CMAKE_CC="clang" CMAKE_CXX="clang++" BUILD_TYPE="Release" COMPILER_FLAGS=""
      os: osx

before_script:
  # print out some version numbers
  - $CMAKE_CXX --version
  - cmake --version

  # configure
  - mkdir build; cd build
  - cmake
      -DCMAKE_BUILD_TYPE="$BUILD_TYPE"
      -DCMAKE_C_COMPILER="$CMAKE_CC" -DCMAKE_CXX_COMPILER="$CMAKE_CXX"
      -DCMAKE_C_FLAGS="$COMPILER_FLAGS" -DCMAKE_CXX_FLAGS="$COMPILER_FLAGS"
      $CMAKE_ARGS ..

script:
  - |
    if [[ "$BUILD_TYPE" == "RelWithDebInfo" && "$CMAKE_CXX" == "g++-6" ]]; then
      make integration_tests;
    else
      make -j4;
    fi
